sudo: false
language: php
php:
  - 7.1
  - 7.2
  - 7.3

install:
  - find . -name \*.php -exec php -l "{}" \;
  - composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-progress
